CREATE TABLE point_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE point_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_code VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    max_earn_amount DECIMAL(15, 0) NOT NULL,
    default_expire_days INT NOT NULL,
    min_expire_days INT NOT NULL,
    max_expire_days INT NOT NULL,
    status VARCHAR(20) NOT NULL,
    status_updated_at TIMESTAMP NOT NULL,
    status_updated_by VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT uq_point_policy_code UNIQUE (policy_code),
    CONSTRAINT chk_point_policy_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT chk_point_policy_values CHECK (
        max_earn_amount >= 1
        AND default_expire_days >= 1
        AND min_expire_days >= 1
        AND max_expire_days >= min_expire_days
        AND max_expire_days <= 1824
    )
);

CREATE TABLE point_user_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_code VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    max_balance_amount DECIMAL(15, 0) NOT NULL,
    status VARCHAR(20) NOT NULL,
    status_updated_at TIMESTAMP NOT NULL,
    status_updated_by VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT uq_point_user_policy_code UNIQUE (policy_code),
    CONSTRAINT chk_point_user_policy_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT chk_point_user_policy_values CHECK (max_balance_amount >= 1)
);

CREATE TABLE point_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    point_user_policy_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    status_updated_at TIMESTAMP NOT NULL,
    status_updated_by VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT uq_point_account_user UNIQUE (user_id),
    CONSTRAINT fk_point_account_user FOREIGN KEY (user_id) REFERENCES point_user(id),
    CONSTRAINT fk_point_account_user_policy FOREIGN KEY (point_user_policy_id) REFERENCES point_user_policy(id),
    CONSTRAINT chk_point_account_status CHECK (status IN ('ACTIVE', 'BLOCKED', 'DELETED'))
);

CREATE TABLE point_balance (
    account_id BIGINT PRIMARY KEY,
    balance_amount DECIMAL(15, 0) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_point_balance_account FOREIGN KEY (account_id) REFERENCES point_account(id),
    CONSTRAINT chk_point_balance_amount CHECK (balance_amount >= 0)
);

CREATE TABLE point_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    point_key VARCHAR(64) NOT NULL,
    account_id BIGINT NOT NULL,
    point_policy_id BIGINT,
    point_user_policy_id BIGINT,
    transaction_type VARCHAR(30) NOT NULL,
    amount DECIMAL(15, 0) NOT NULL,
    order_no VARCHAR(100),
    related_transaction_id BIGINT,
    created_by_type VARCHAR(20) NOT NULL,
    created_by_id VARCHAR(64),
    reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT uq_point_tx_key UNIQUE (point_key),
    CONSTRAINT fk_point_tx_account FOREIGN KEY (account_id) REFERENCES point_account(id),
    CONSTRAINT fk_point_tx_point_policy FOREIGN KEY (point_policy_id) REFERENCES point_policy(id),
    CONSTRAINT fk_point_tx_user_policy FOREIGN KEY (point_user_policy_id) REFERENCES point_user_policy(id),
    CONSTRAINT fk_point_tx_related FOREIGN KEY (related_transaction_id) REFERENCES point_transaction(id),
    CONSTRAINT chk_point_tx_type CHECK (transaction_type IN ('EARN', 'EARN_CANCEL', 'USE', 'USE_CANCEL', 'EXPIRE')),
    CONSTRAINT chk_point_tx_created_by CHECK (created_by_type IN ('USER', 'ADMIN', 'SYSTEM')),
    CONSTRAINT chk_point_tx_amount CHECK (amount > 0)
);

CREATE TABLE point_idempotency (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    request_type VARCHAR(30) NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    request_hash VARCHAR(128) NOT NULL,
    transaction_id BIGINT,
    status VARCHAR(20) NOT NULL,
    error_code VARCHAR(100),
    error_message VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT uq_point_idempotency_key UNIQUE (account_id, request_type, idempotency_key),
    CONSTRAINT fk_point_idempotency_account FOREIGN KEY (account_id) REFERENCES point_account(id),
    CONSTRAINT fk_point_idempotency_tx FOREIGN KEY (transaction_id) REFERENCES point_transaction(id),
    CONSTRAINT chk_point_idempotency_type CHECK (request_type IN ('EARN', 'EARN_CANCEL', 'USE', 'USE_CANCEL', 'EXPIRE')),
    CONSTRAINT chk_point_idempotency_status CHECK (status IN ('PROCESSING', 'SUCCESS', 'FAILED')),
    CONSTRAINT chk_point_idempotency_success CHECK (
        status <> 'SUCCESS' OR transaction_id IS NOT NULL
    ),
    CONSTRAINT chk_point_idempotency_failed CHECK (
        status <> 'FAILED' OR error_code IS NOT NULL
    )
);

CREATE TABLE point_key_sequence (
    date_key VARCHAR(6) PRIMARY KEY,
    next_value BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT chk_point_key_sequence_value CHECK (next_value >= 1)
);

CREATE TABLE point_earn (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    earn_type VARCHAR(40) NOT NULL,
    earn_amount DECIMAL(15, 0) NOT NULL,
    available_amount DECIMAL(15, 0) NOT NULL,
    consumed_amount DECIMAL(15, 0) NOT NULL DEFAULT 0,
    cancelled_amount DECIMAL(15, 0) NOT NULL DEFAULT 0,
    expired_amount DECIMAL(15, 0) NOT NULL DEFAULT 0,
    expires_at TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL,
    original_earn_id BIGINT,
    source_usage_cancel_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT uq_point_earn_tx UNIQUE (transaction_id),
    CONSTRAINT fk_point_earn_tx FOREIGN KEY (transaction_id) REFERENCES point_transaction(id),
    CONSTRAINT fk_point_earn_account FOREIGN KEY (account_id) REFERENCES point_account(id),
    CONSTRAINT fk_point_earn_original FOREIGN KEY (original_earn_id) REFERENCES point_earn(id),
    CONSTRAINT chk_point_earn_type CHECK (earn_type IN ('NORMAL', 'MANUAL', 'USE_CANCEL_RESTORE')),
    CONSTRAINT chk_point_earn_status CHECK (status IN ('AVAILABLE', 'EXHAUSTED', 'CANCELED', 'EXPIRED')),
    CONSTRAINT chk_point_earn_amount CHECK (
        earn_amount > 0
        AND available_amount >= 0
        AND consumed_amount >= 0
        AND cancelled_amount >= 0
        AND expired_amount >= 0
        AND earn_amount = available_amount + consumed_amount + cancelled_amount + expired_amount
    ),
    CONSTRAINT chk_point_earn_expires_at CHECK (expires_at > created_at)
);

CREATE TABLE point_earn_cancel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    earn_id BIGINT NOT NULL,
    cancel_amount DECIMAL(15, 0) NOT NULL,
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT uq_earn_cancel_tx UNIQUE (transaction_id),
    CONSTRAINT uq_earn_cancel_earn UNIQUE (earn_id),
    CONSTRAINT fk_earn_cancel_tx FOREIGN KEY (transaction_id) REFERENCES point_transaction(id),
    CONSTRAINT fk_earn_cancel_account FOREIGN KEY (account_id) REFERENCES point_account(id),
    CONSTRAINT fk_earn_cancel_earn FOREIGN KEY (earn_id) REFERENCES point_earn(id),
    CONSTRAINT chk_earn_cancel_amount CHECK (cancel_amount > 0)
);

CREATE TABLE point_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    order_no VARCHAR(100) NOT NULL,
    usage_amount DECIMAL(15, 0) NOT NULL,
    cancelled_amount DECIMAL(15, 0) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT uq_point_usage_tx UNIQUE (transaction_id),
    CONSTRAINT uq_point_usage_order UNIQUE (account_id, order_no),
    CONSTRAINT fk_point_usage_tx FOREIGN KEY (transaction_id) REFERENCES point_transaction(id),
    CONSTRAINT fk_point_usage_account FOREIGN KEY (account_id) REFERENCES point_account(id),
    CONSTRAINT chk_point_usage_status CHECK (status IN ('USED', 'PARTIAL_CANCELED', 'CANCELED')),
    CONSTRAINT chk_point_usage_amount CHECK (
        usage_amount > 0
        AND cancelled_amount >= 0
        AND cancelled_amount <= usage_amount
    )
);

CREATE TABLE point_usage_allocation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usage_id BIGINT NOT NULL,
    earn_id BIGINT NOT NULL,
    allocation_seq INT NOT NULL,
    amount DECIMAL(15, 0) NOT NULL,
    cancelled_amount DECIMAL(15, 0) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT uq_usage_alloc_seq UNIQUE (usage_id, allocation_seq),
    CONSTRAINT uq_usage_alloc_earn UNIQUE (usage_id, earn_id),
    CONSTRAINT fk_usage_alloc_usage FOREIGN KEY (usage_id) REFERENCES point_usage(id),
    CONSTRAINT fk_usage_alloc_earn FOREIGN KEY (earn_id) REFERENCES point_earn(id),
    CONSTRAINT chk_usage_alloc_status CHECK (status IN ('USED', 'PARTIAL_CANCELED', 'CANCELED')),
    CONSTRAINT chk_usage_alloc_amount CHECK (
        amount > 0
        AND cancelled_amount >= 0
        AND cancelled_amount <= amount
    )
);

CREATE TABLE point_usage_cancel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    usage_id BIGINT NOT NULL,
    cancel_amount DECIMAL(15, 0) NOT NULL,
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT uq_usage_cancel_tx UNIQUE (transaction_id),
    CONSTRAINT fk_usage_cancel_tx FOREIGN KEY (transaction_id) REFERENCES point_transaction(id),
    CONSTRAINT fk_usage_cancel_account FOREIGN KEY (account_id) REFERENCES point_account(id),
    CONSTRAINT fk_usage_cancel_usage FOREIGN KEY (usage_id) REFERENCES point_usage(id),
    CONSTRAINT chk_usage_cancel_amount CHECK (cancel_amount > 0)
);

ALTER TABLE point_earn
ADD CONSTRAINT fk_point_earn_source_usage_cancel
FOREIGN KEY (source_usage_cancel_id) REFERENCES point_usage_cancel(id);

CREATE TABLE point_usage_cancel_allocation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usage_cancel_id BIGINT NOT NULL,
    usage_allocation_id BIGINT NOT NULL,
    original_earn_id BIGINT NOT NULL,
    restored_earn_id BIGINT NOT NULL,
    cancel_amount DECIMAL(15, 0) NOT NULL,
    restore_type VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT uq_cancel_alloc_usage_alloc UNIQUE (usage_cancel_id, usage_allocation_id),
    CONSTRAINT fk_cancel_alloc_cancel FOREIGN KEY (usage_cancel_id) REFERENCES point_usage_cancel(id),
    CONSTRAINT fk_cancel_alloc_usage_alloc FOREIGN KEY (usage_allocation_id) REFERENCES point_usage_allocation(id),
    CONSTRAINT fk_cancel_alloc_original_earn FOREIGN KEY (original_earn_id) REFERENCES point_earn(id),
    CONSTRAINT fk_cancel_alloc_restored_earn FOREIGN KEY (restored_earn_id) REFERENCES point_earn(id),
    CONSTRAINT chk_cancel_alloc_restore_type CHECK (restore_type IN ('ORIGINAL_EARN', 'NEW_EARN')),
    CONSTRAINT chk_cancel_alloc_amount CHECK (cancel_amount > 0)
);

CREATE TABLE point_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    earn_id BIGINT,
    usage_id BIGINT,
    usage_cancel_id BIGINT,
    usage_allocation_id BIGINT,
    ledger_type VARCHAR(50) NOT NULL,
    delta_amount DECIMAL(15, 0) NOT NULL,
    account_balance_before DECIMAL(15, 0) NOT NULL,
    account_balance_after DECIMAL(15, 0) NOT NULL,
    earn_available_before DECIMAL(15, 0),
    earn_available_after DECIMAL(15, 0),
    description VARCHAR(500),
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_ledger_tx FOREIGN KEY (transaction_id) REFERENCES point_transaction(id),
    CONSTRAINT fk_ledger_account FOREIGN KEY (account_id) REFERENCES point_account(id),
    CONSTRAINT fk_ledger_earn FOREIGN KEY (earn_id) REFERENCES point_earn(id),
    CONSTRAINT fk_ledger_usage FOREIGN KEY (usage_id) REFERENCES point_usage(id),
    CONSTRAINT fk_ledger_usage_cancel FOREIGN KEY (usage_cancel_id) REFERENCES point_usage_cancel(id),
    CONSTRAINT fk_ledger_usage_alloc FOREIGN KEY (usage_allocation_id) REFERENCES point_usage_allocation(id),
    CONSTRAINT chk_ledger_type CHECK (ledger_type IN (
        'EARN_INCREASE',
        'EARN_CANCEL_DECREASE',
        'USE_DECREASE',
        'USE_CANCEL_ORIGINAL_INCREASE',
        'USE_CANCEL_NEW_EARN_INCREASE',
        'EXPIRE_DECREASE'
    )),
    CONSTRAINT chk_ledger_delta CHECK (delta_amount <> 0),
    CONSTRAINT chk_ledger_account_balance CHECK (
        account_balance_before >= 0
        AND account_balance_after >= 0
        AND account_balance_after = account_balance_before + delta_amount
    ),
    CONSTRAINT chk_ledger_earn_available_before CHECK (
        earn_available_before IS NULL OR earn_available_before >= 0
    ),
    CONSTRAINT chk_ledger_earn_available_after CHECK (
        earn_available_after IS NULL OR earn_available_after >= 0
    )
);

CREATE INDEX idx_point_tx_account_created
ON point_transaction(account_id, created_at, id);

CREATE INDEX idx_point_tx_related
ON point_transaction(related_transaction_id);

CREATE INDEX idx_point_tx_order
ON point_transaction(order_no);

CREATE INDEX idx_point_idempotency_account_status
ON point_idempotency(account_id, status, created_at);

CREATE INDEX idx_point_earn_use
ON point_earn(account_id, status, expires_at, id);

CREATE INDEX idx_point_earn_balance_group
ON point_earn(account_id, status, expires_at, earn_type);

CREATE INDEX idx_point_earn_expire
ON point_earn(status, expires_at);

CREATE INDEX idx_point_usage_account_order
ON point_usage(account_id, order_no);

CREATE INDEX idx_usage_alloc_usage
ON point_usage_allocation(usage_id);

CREATE INDEX idx_usage_alloc_earn
ON point_usage_allocation(earn_id);

CREATE INDEX idx_usage_cancel_usage
ON point_usage_cancel(usage_id);

CREATE INDEX idx_cancel_alloc_cancel
ON point_usage_cancel_allocation(usage_cancel_id);

CREATE INDEX idx_cancel_alloc_usage_alloc
ON point_usage_cancel_allocation(usage_allocation_id);

CREATE INDEX idx_ledger_account_created
ON point_ledger(account_id, created_at, id);

CREATE INDEX idx_ledger_tx
ON point_ledger(transaction_id);

CREATE INDEX idx_ledger_usage_cancel
ON point_ledger(usage_cancel_id, ledger_type, id);
